version: '3.4'

services:
  weatherapp:
    image: weatherapp
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: weatherapp
    environment:
      NODE_ENV: production
      PORT: $PORT
      OPEN_WEATHER_API_KEY: $OPEN_WEATHER_API_KEY
    ports:
      - "8080:8080"
