version: '3.4'

services:
  weatherapp:
    image: weatherapp_test
    build:
      context: .
      dockerfile: ./Dockerfile-test
    container_name: test
    environment:
      NODE_ENV: test
    command: npm run test
